2023-12-20 16:19:08,312 - INFO - main.py:5 - Bot started!
2023-12-20 17:18:52,117 - INFO - api_call.py:29 - API POST request for projects failed with error 400 Client Error: Bad Request for url: https://dqpllfj7tb.execute-api.us-east-1.amazonaws.com/dev/projects
2023-12-20 18:52:08,997 - INFO - main.py:6 - Bot started!
2023-12-20 18:52:27,007 - INFO - main.py:6 - Bot started!
2023-12-20 18:55:01,320 - INFO - main.py:6 - Bot started!
2023-12-20 19:14:05,275 - INFO - main.py:6 - Bot started!
2023-12-20 19:34:02,283 - INFO - main.py:6 - Bot started!
2023-12-20 19:44:44,807 - INFO - main.py:6 - Bot started!
2023-12-20 19:49:29,258 - INFO - main.py:6 - Bot started!
2023-12-20 19:50:27,270 - WARNING - main.py:9 - Update "{'message': {'new_chat_photo': [], 'new_chat_members': [], 'date': 1703101827, 'chat': {'type': 'private', 'username': 'realtalishaw', 'first_name': 'Talisha', 'id': 5915765775, 'last_name': 'White'}, 'entities': [], 'photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'message_id': 64, 'channel_chat_created': False, 'text': '07-20-1993', 'caption_entities': [], 'supergroup_chat_created': False, 'from': {'first_name': 'Talisha', 'last_name': 'White', 'id': 5915765775, 'language_code': 'en', 'is_bot': False, 'username': 'realtalishaw'}}, 'update_id': 978925644}" caused error "Object of type File is not JSON serializable"
2023-12-20 19:52:50,644 - INFO - main.py:6 - Bot started!
2023-12-21 00:50:06,868 - INFO - main.py:6 - Bot started!
2023-12-21 01:27:09,301 - INFO - main.py:6 - Bot started!
2023-12-21 01:39:40,342 - INFO - main.py:6 - Bot started!
2023-12-21 01:40:22,427 - WARNING - main.py:9 - Update "{'callback_query': {'id': '6961276460918830911', 'data': 'yes', 'message': {'new_chat_photo': [], 'new_chat_members': [], 'reply_markup': {'inline_keyboard': [[{'text': 'Yes', 'callback_data': 'yes'}, {'text': 'No', 'callback_data': 'no'}]]}, 'photo': [], 'channel_chat_created': False, 'chat': {'username': 'realtalishaw', 'id': 5915765775, 'last_name': 'White', 'first_name': 'Talisha', 'type': 'private'}, 'text': 'Is this information correct?', 'entities': [], 'message_id': 119, 'date': 1703122819, 'supergroup_chat_created': False, 'group_chat_created': False, 'delete_chat_photo': False, 'caption_entities': [], 'from': {'username': 'theometricsbot', 'is_bot': True, 'id': 6887127186, 'first_name': 'TheoBot'}}, 'chat_instance': '-3241866149608258687', 'from': {'language_code': 'en', 'username': 'realtalishaw', 'is_bot': False, 'id': 5915765775, 'last_name': 'White', 'first_name': 'Talisha'}}, 'update_id': 978925677}" caused error "'NoneType' object has no attribute 'reply_text'"
2023-12-21 01:42:07,410 - INFO - main.py:6 - Bot started!
2023-12-21 01:44:08,849 - WARNING - main.py:9 - Update "{'callback_query': {'chat_instance': '-3241866149608258687', 'message': {'entities': [], 'text': 'Is this information correct?', 'new_chat_members': [], 'delete_chat_photo': False, 'chat': {'first_name': 'Talisha', 'username': 'realtalishaw', 'last_name': 'White', 'id': 5915765775, 'type': 'private'}, 'new_chat_photo': [], 'supergroup_chat_created': False, 'group_chat_created': False, 'date': 1703123045, 'photo': [], 'channel_chat_created': False, 'message_id': 135, 'reply_markup': {'inline_keyboard': [[{'text': 'Yes', 'callback_data': 'yes'}, {'text': 'No', 'callback_data': 'no'}]]}, 'caption_entities': [], 'from': {'username': 'theometricsbot', 'id': 6887127186, 'is_bot': True, 'first_name': 'TheoBot'}}, 'id': '6961276463880568813', 'data': 'yes', 'from': {'username': 'realtalishaw', 'language_code': 'en', 'last_name': 'White', 'id': 5915765775, 'is_bot': False, 'first_name': 'Talisha'}}, 'update_id': 978925686}" caused error "'NoneType' object has no attribute 'reply_text'"
2023-12-21 02:18:19,900 - INFO - main.py:6 - Bot started!
2023-12-21 02:20:01,421 - WARNING - main.py:9 - Update "{'update_id': 978925695, 'callback_query': {'id': '6961276464358990833', 'chat_instance': '-3241866149608258687', 'data': 'yes', 'message': {'photo': [], 'new_chat_photo': [], 'date': 1703125198, 'chat': {'last_name': 'White', 'id': 5915765775, 'first_name': 'Talisha', 'username': 'realtalishaw', 'type': 'private'}, 'reply_markup': {'inline_keyboard': [[{'callback_data': 'yes', 'text': 'Yes'}, {'callback_data': 'no', 'text': 'No'}]]}, 'delete_chat_photo': False, 'group_chat_created': False, 'new_chat_members': [], 'text': 'Is this information correct?', 'supergroup_chat_created': False, 'message_id': 152, 'caption_entities': [], 'channel_chat_created': False, 'entities': [], 'from': {'id': 6887127186, 'is_bot': True, 'first_name': 'TheoBot', 'username': 'theometricsbot'}}, 'from': {'id': 5915765775, 'language_code': 'en', 'is_bot': False, 'first_name': 'Talisha', 'last_name': 'White', 'username': 'realtalishaw'}}}" caused error "'NoneType' object has no attribute 'reply_text'"
2023-12-21 02:23:55,336 - INFO - main.py:6 - Bot started!
2023-12-21 02:25:19,337 - WARNING - main.py:9 - Update "{'update_id': 978925705, 'callback_query': {'id': '6961276461351290659', 'data': 'yes', 'chat_instance': '-3241866149608258687', 'message': {'group_chat_created': False, 'caption_entities': [], 'message_id': 170, 'date': 1703125515, 'entities': [], 'new_chat_members': [], 'delete_chat_photo': False, 'text': 'Is this information correct?', 'photo': [], 'new_chat_photo': [], 'chat': {'id': 5915765775, 'first_name': 'Talisha', 'username': 'realtalishaw', 'last_name': 'White', 'type': 'private'}, 'supergroup_chat_created': False, 'channel_chat_created': False, 'reply_markup': {'inline_keyboard': [[{'callback_data': 'yes', 'text': 'Yes'}, {'callback_data': 'no', 'text': 'No'}]]}, 'from': {'username': 'theometricsbot', 'id': 6887127186, 'is_bot': True, 'first_name': 'TheoBot'}}, 'from': {'username': 'realtalishaw', 'id': 5915765775, 'last_name': 'White', 'language_code': 'en', 'is_bot': False, 'first_name': 'Talisha'}}}" caused error "'NoneType' object has no attribute 'reply_text'"
2023-12-21 02:27:33,145 - INFO - main.py:6 - Bot started!
2023-12-21 02:27:57,181 - INFO - main.py:6 - Bot started!
2023-12-21 02:28:16,873 - INFO - main.py:6 - Bot started!
2023-12-21 02:31:10,500 - INFO - main.py:6 - Bot started!
2023-12-21 03:01:13,476 - INFO - main.py:7 - Bot started!
2023-12-21 03:02:44,665 - INFO - main.py:7 - Bot started!
2023-12-21 03:05:31,598 - WARNING - main.py:10 - Update "{'update_id': 978925717, 'message': {'message_id': 193, 'date': 1703127931, 'supergroup_chat_created': False, 'chat': {'first_name': 'Talisha', 'type': 'private', 'last_name': 'White', 'id': 5915765775, 'username': 'realtalishaw'}, 'delete_chat_photo': False, 'new_chat_photo': [], 'text': '/register', 'entities': [{'offset': 0, 'length': 9, 'type': 'bot_command'}], 'caption_entities': [], 'photo': [], 'group_chat_created': False, 'channel_chat_created': False, 'new_chat_members': [], 'from': {'first_name': 'Talisha', 'id': 5915765775, 'username': 'realtalishaw', 'language_code': 'en', 'is_bot': False, 'last_name': 'White'}}}" caused error "name 'InlineKeyboardButton' is not defined"
2023-12-21 03:05:42,745 - WARNING - main.py:10 - Update "{'update_id': 978925720, 'message': {'message_id': 198, 'date': 1703127942, 'supergroup_chat_created': False, 'chat': {'first_name': 'Talisha', 'type': 'private', 'last_name': 'White', 'id': 5915765775, 'username': 'realtalishaw'}, 'delete_chat_photo': False, 'new_chat_photo': [], 'text': '/register', 'entities': [{'offset': 0, 'length': 9, 'type': 'bot_command'}], 'caption_entities': [], 'photo': [], 'group_chat_created': False, 'channel_chat_created': False, 'new_chat_members': [], 'from': {'first_name': 'Talisha', 'id': 5915765775, 'username': 'realtalishaw', 'language_code': 'en', 'is_bot': False, 'last_name': 'White'}}}" caused error "name 'InlineKeyboardButton' is not defined"
2023-12-21 03:27:28,851 - INFO - main.py:7 - Bot started!
2023-12-21 03:31:52,847 - INFO - main.py:7 - Bot started!
2023-12-21 03:36:41,479 - WARNING - main.py:10 - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2023-12-21 03:36:46,723 - WARNING - main.py:10 - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
